name: 'Apply Terraform'
description: 'Apply Terraform Using Google OIDC'
inputs:
  cosmos_name:
    description: 'Cosmos Name'
    required: true
  realm_name:
    description: 'Realm name'
    required: true
  app_name:
    description: 'Application name'
    required: true
  env_name:
    description: 'Environment Name'
    required: true
  project_id:
    description: 'Project ID'
    required: true
  workload_identity_provider:
    description: 'Workload Identity Provider Name'
    required: true
  service_account:
    description: 'Related Service Account Name'
    required: true
  tf_bucket_name:
    description: 'State terraform bucket name'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        project_id: ${{ inputs.project_id }}
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: Terraform Init
      shell: bash
      run: |
        terraform -chdir=iac/environments/${{ inputs.env_name }} init \
          -backend-config="bucket=${{ inputs.tf_bucket_name }}" \
          -backend-config="prefix=${{ inputs.realm_name }}/${{ inputs.foundation_name }}/${{ inputs.app_name }}/${{ inputs.env_name }}/terraform/state"
