name: Deploy - Pypi - Repository

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prd
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Main Step
        uses: ./.github/actions/main
