name: Workflow - PRD

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prd
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Infrastructure
        uses: ./.github/actions/iac

      - name: Publish PYPI
        uses: ./.github/actions/module-pypi/publish