name: Workflow - DEV

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: false
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
